"""create invitations table

Revision ID: 72ef3ba5c532
Revises: 79920c59d7cc
Create Date: 2026-03-28 15:40:16.687583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ef3ba5c532'
down_revision: Union[str, None] = '79920c59d7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('invitation_id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=40), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('invite_token', sa.String(length=80), nullable=False),
    sa.Column('invite_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('invitation_id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index(op.f('ix_invitations_batch_id'), 'invitations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_invitations_campaign_id'), 'invitations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_invitations_tenant_id'), 'invitations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitations_tenant_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_campaign_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_batch_id'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
