"""create invitation batches table

Revision ID: 79920c59d7cc
Revises: 8e64df651f78
Create Date: 2026-03-27 23:47:11.332799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79920c59d7cc'
down_revision: Union[str, None] = '8e64df651f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_batches',
    sa.Column('batch_id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_invitation_batches_campaign_id'), 'invitation_batches', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_invitation_batches_tenant_id'), 'invitation_batches', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_batches_tenant_id'), table_name='invitation_batches')
    op.drop_index(op.f('ix_invitation_batches_campaign_id'), table_name='invitation_batches')
    op.drop_table('invitation_batches')
    # ### end Alembic commands ###
