"""create campaign audience participants table

Revision ID: 8e64df651f78
Revises: 
Create Date: 2026-03-27 21:03:14.596900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e64df651f78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_audience_participants',
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_index(op.f('ix_campaign_audience_participants_campaign_id'), 'campaign_audience_participants', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_audience_participants_tenant_id'), 'campaign_audience_participants', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_audience_participants_tenant_id'), table_name='campaign_audience_participants')
    op.drop_index(op.f('ix_campaign_audience_participants_campaign_id'), table_name='campaign_audience_participants')
    op.drop_table('campaign_audience_participants')
    # ### end Alembic commands ###
